development: 
  adapter: postgresql
  database: depot_development
  pool: 5
  timeout: 5000
  username: depot
  password: depot
test: 
  adapter: postgresql
  database: depot_test
  pool: 5
  timeout: 5000
  username: depot
  password: depot